### PR TITLE
Change 6to5ify to babelify

### PR DESCRIPTION
**Pull request by megakote**

### CODE REVIEW

**Comment by mquan** [comment]
Why do we need the polyfill for tests and examples?

**Comment by megakote** [comment]
6to5 convert `for…of`' to `Symbol.iterator`
Safari, FF, IE and node v0.10.36 doesn't have `Symbol.iterator` implementation
2015-02-26_a3b1iikc3f1suxv

**Comment by mquan** [comment]
Thanks for the info. I don't really like the idea of making the polyfill a cortex dependency. Will try to make it work without it for now.

**Comment by mquan** [comment]
@megakote I revert back to the regular for loop, you can rebase and make the babel upgrade without the polyfill dependecy. Thanks

**Comment by megakote** [comment]
Done

**Pull request merged**
