### PR TITLE
simultaneous changes propagate through a single branch only

### PR DESCRIPTION
**Pull request by aleksxor**
to illistrate the problem when simultaneous changes on the same root affect only the single branch http://jsbin.com/kuxopu/4/edit?html,js,output

### CODE REVIEW

**Comment by mquan** [comment]
Can you explain the issue here, it's not clear what you're trying to show in jsbin.

**Comment by aleksxor** [comment]
When two (or more) data branches (as foo and bar in the example) have a common root then simultaneous changes in both branches over the single javascript stack frame would result in only one of them would get the `__changes` set. Thus we cannot fully rely on `didChange()`.

**Comment by aleksxor** [comment]
`ecf9c5b` included cortex script in jsbin is just the last built version (0.8.6). since there are no built scripts right now in the repository.

**Comment by mquan** [comment]
I see, thanks. You can run `gulp` to build it, please build it this way. Can you also write some specs for this fix. Let me know if you need any help. You can run spec with `gulp test`

**Comment by aleksxor** [comment]
Added specs. Squashed into a single commit and rebased over your recent changes. Just looks like I've got a slightly newer version of `deep-diff` installed locally.

**Comment by mquan** [comment]
Great job. Thanks

**Pull request merged**
