### PR TITLE
Add commit method

### PR DESCRIPTION
**Pull request by megakote**

### CODE REVIEW

**Comment by mquan** [comment]
Can you explain how this is used? Because in order for this to work you'd need to set the `__updates` array and currently there is no public method to do that.

**Comment by megakote** [comment]
I need `commit` to apply `__updates` to cortex in sync mode. 
This example didn't work `cortex.add('c', {'d': 1});
cortex.c.d.getValue();`

**Comment by mquan** [comment]
it doesn't work because `batchAll` is run at the end of the run loop. You should perform your read in the callback method you define for cortex.

But I'm curious why you need to update your cortex object and read it immediately after. Are you using it outside the scope of your react component.

**Comment by mquan** [comment]
If you have to manually call `commit` then you will also end up with another `batchAll` when the actual call happen. This means inefficient rewrapping and double callbacks run.

You can define multiple callbacks for your cortex object, that's the approach you should pursue.

**Comment by megakote** [comment]
> Are you using it outside the scope of your react component.

I use cortex as store in flux-like architecture. 

> This means inefficient rewrapping and double callbacks run.

oops…i update method to avoid this

**Comment by mquan** [comment]
I still don't think you need this method. It breaks the normal flow for the regular use case. Just add a new callback for reading back data.

**Comment by megakote** [comment]
I need write to cortex from React component constructor. 
For example: 

    constructor(props, css) {
        super(props);
    this.setInitialState = this.setInitialState.bind(this);
    if (typeof css !== 'undefined') this.css = css;
       }



In render i use this data, how callback can help me?

**Comment by megakote** [comment]
I need write to cortex from component constructor. 

For example: 

    constructor(props) {
      if (typeof Cortex.component === 'undefined')
        Cortex.set({component: default_value});
    }

     render() {
      // use Cortex.component
    } 

How callback can help me?

**Comment by mquan** [comment]
I'm not sure I understand what you're trying to do. Is that snippet part of a new class or a react component? Is Cortex your cortex object, if so wouldn't it override the Cortex lib? Can't you just do this?

```javascript
var YourComponent = React.createClass({
  getDefaultProps: function() {
    // if this.props.myData isn't set then it will use this value as default
    return {
      myData: defaultData
    };
 },

render: function() {
  // use this.props.myData
}
```

**Comment by megakote** [comment]
Update code snippet for more understand.
In your example this.props.myData in not a DataWrapper object, in render your cannot use getValue/set/etc.

**Comment by mquan** [comment]
The problem I have with having a `commit` method is it requires user to know too much about cortex internals (event loop and such) and it requires you to keep calling commit every time you do a sync set. There are several ways to achieve what you want.

1. you could initialize `cortex.component` when you initialize cortex. This is similar to what you're doing since you have to do it in the constructor anyway, why not do it on cortex initialization

2. you can declaratively define it in render. I personally prefer this as it's what react was designed to do.
```javascript
render: function() {
  if this.props.cortex.component {
   // use this.props.cortex.component
  } else {
   // use default value
  }
}
```

3. you could create separate cortex objects for each top level object. It looks like you are nesting several independent objects under the same cortex. If you use one cortex for each object then you can utilize `getDefaultProps` to set default values

```javascript
getDefaultProps: function() {
  return {
   component: new Cortex({foo: "bar"}),
   somethingElse: new Cortex({foo: "baz"})
  };
}
```

**Comment by megakote** [comment]
> it requires you to keep calling commit every time you do a sync set. 

Using `commit` can be optional. It's only reset next `__batchAll` an run it in sync mode, I don't see any contradictions, problem with performance or broken backward compatibility.

> when you initialize cortex

I can not, in my structure only component know it's default value. And I have a lot of React components. Initialize cortex size will be very big.

> you can declaratively define it in render.

it's very bad decision. `render` method will be very complex. React component listen Cortex and run render on callback (double render on start).

> you could create separate cortex objects for each top level object.

I can not separate Cortex. I use it to share state between components.

**Comment by mquan** [comment]
> I can not separate Cortex. I use it to share state between components.

This sounds wrong, you cannot have two different components setting default for the same object. It will cause race condition. Having a component managing cortex while other components also concurrently doing so it a bad design choice. Even when you know for sure only one component manage the default of a given object it's still a bad idea because you don't know where's the source of truth.

If all your components use everything defined in cortex then you can definitely set default at initialization. If your components only use a subset of the current cortex object then you just need to pass in the right object instead of passing everything that some components may not use.

**Comment by mquan** [comment]
Closing since there're better alternative solutions.

**Pull request closed without merging**
